---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-server-sso
  namespace: runbooks
spec:
  encryptedData:
    client-id: AgAtfHpfwVJGeZU8pMMvLUbyWrYXx+kGXbfYLOCCqbt05GOk1cDekS+1yaep7sE3zLaW8yUHTAxHDVlZszpjDzVyVfSnUCEApo8vpW4t0zIqKSH9IvSlRbGmerUF1UUcm0eF8M5HDVhD6yGmR5+s+eAMJY6/pVyWrpEjI/DEsKxN1CyQVtPNDbp2dskmGJlysGQaFxNm1qxQUrxSvq7jFuAUSbYSfSWPtFCOGfLGA3Dl50BA5aMSCNh1KD0dkTlhqO3oyqR2q/2PnGJpk2eVi38865Eh0dAKly5TJkTqA0fwA1oZ2RvEN5AEUGRL2pzi0rWZjP1/s8heEK2QNe1PspqC/dOM4EGM6yWjP1E+lBgndTpGDoV0a9/fK0nyFu/SKiy4DespchpBOhaUmelr8Rl/DKOGWyRCCf6wqBtxNJa0jBz7Phq5PLfeS8xNfgaRYPsD4Kt1BwoGYaU5S0Xx/MhKxQSRIZ6c3fC2afo70cmObNZ9Hk1gB4ruopj5cKqzpY6IBTeyjG/t/5gaYGCpOmFne8vVh41KdizgwkKGgmC02Dn5kT3nWImUeY7PufoQ/r1UgnLrKw2eK+J0FOWIQDhPAD+4tyjLXdTPQ3SOlM5h39C0SVq94+QFXjmnTXP64J1Z3LtQTmmu6T+lz+fov1qjiD9mN+PeWhbqDBpDeVW2qk66UcbuJL0xlzuqAJG7+YP0VlasP91KUim1ELdiGs5ZdGZbyhxPSWx7TELTEwF8vwIeXZA=
    client-secret: AgBbdwKxLaFGosocX2EeSd/PCjGbha0tk4hqwB+VFl3veJnYgfHcC1wS1ICrOhfIldmABxcwj5dGyF0ndmAEbn0zvrviLQBawbntoNFvATrqPbSdBuG9geXY99epZVKpjRILKSCg4PRk7NzjH8iyRWFMb2PQRt80jjR+whc7uvFcGMzySFGeeCIHhkIIjK2VxAcW+pn/r5BChQF8JMgJoxPW7G3zYt8godKpbbOVGFr3zWug4U4BVguLCVnGJaWZVfygAyvaDrPpuIjx/g0jV6qCUyU+wcxBvFQkdlwlt4yaHLSg4gdjtiRFKs0Q7AVMDUDjGVn8Ma9qaHPUh7KaulFDrAS+F3AsBJz6Vk9W+zwTlzmw3JEPubrPmEZ4aV+dsE3VetaQpZ3rzDK7TLumMn2cdr9iFSMVF1TTmEhCpjrweClGGyXItA7AFsxPDJtreOA52idI7AI/fCoZ574QWV4ACdeBEzHE1gQRTz+eTd0kVoJSEYnP/O9HwevY/nXXecduLQ/iBtD57CBziLx1dfoCFJOQwn+U70VZlX5ZcHxmE9tbpMYKRMDMeHEit2SiJd3qhWugB5s/6m84kEYqN6MLC3NooNtKePdgj6kTVSYugLaPw3K/DXNC2AcuPVH+C6ZTQ8jzphRVHIaL6wjcgD9YGjvzGd77SFWELkGAIcT9uQqM2OrsT1vtdhdTBx5Z5OofYxw9NhKfkeRY9PNG3iNteGuTnMqu8c3QPBFO+E8yWbKKhJYTQSH1
  template:
    metadata:
      name: argo-server-sso
      namespace: runbooks
