apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: runbookscd
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # CRDs + controller first
spec:
  project: default
  source:
    repoURL: https://github.com/pt-vamshi/argo-flow.git
    targetRevision: main
    path: manifests/argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: runbooks
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true     # the Argo install has large CRDs
