apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # creates argo-l3 / runbook-demo-dev + SAs/roles
spec:
  project: default
  source:
    repoURL: https://github.com/pt-vamshi/argo-flow.git
    targetRevision: main
    path: manifests/rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated: { prune: true, selfHeal: true }
